pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'court-crawler:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
  - script: |
      docker build -f Dockerfile -t $(dockerId)/$(imageName) .
      docker login -u $(dockerId) -p $pswd
      docker push $(dockerId)/$(imageName)
    env:
      pswd: $(dockerPassword)
    displayName: Build docker image and push to Docker Hub
